config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/unprocessable_entity'

  get 'errors/internal_server_error'

  get 'errors/bad_request'

  resources :artists do
    member do
      patch '/favorite', action: 'favorite'
    end
  end

  resources :records do
    member do
      patch '/favorite', action: 'favorite'
    end
    resources :songs do
      member do
        patch '/favorite', action: 'favorite'
      end
    end
  end

  # account creation routes
  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  # session control routes
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  # root of the application
  root to: 'records#index'
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  include MarkAsFavorite

  has_and_belongs_to_many :records
  has_many :songs, through: :records

  validates :name, presence: true, length: { minimum: 1 }

  def songs_by_record
    songs.map.with_object(Hash.new { |hash, key| hash[key] = [] }) do |song, hash|
      hash[song.record] << song
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :password,
    length: { minimum: 8, if: :validate_password? },
    confirmation: { if: :validate_password? }
  validates :email, presence: true, uniqueness: true
  validates :name, presence: true, length: { minimum: 1 }

  has_many :records
  has_many :artists, through: :records
  has_many :songs, through: :records

private
  def validate_password?
    new_record? || (password.present? || password_confirmation.present?)
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy, :favorite]
  before_filter :authorize
  include MarkingFavorites

  def model
    @artist
  end

  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all.
      includes(:records).
      page(params[:page]).
      per(params[:per_page] || 5)
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)
    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if artist_params.present? && @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.includes(:records).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:name)
    end
end

app/views/artists/_form.html.erb
<%= form_for @artist, html: {class: 'form form-horizontal'} do |f| %>
  <div class='row'>
    <div class='col-sm-4'>
      <%= render partial: 'shared/form_field', locals: { form: f, model: @artist, field_name: :name, field_type: :text_field, tab_index: 1 } %>
    </div>
  </div>
  <div class='row'>
    <div class='col-sm-offset-1 col-sm-2>'>
      <%= render partial: 'shared/submission_button', locals: { form: f, text: 'Save', tab_index: 2 } %>
    </div>
  </div>
<% end %>

app/views/artists/edit.html.erb
<table class='table table-condensed record-short'>
  <tbody>
    <tr>
      <td class='image'>
        <div class='record img-circle'>
        </div>
      </td>
      <td class='link'>
        <%= favorite_widget @artist, favorite_artist_path(@artist) %>
        <%= link_to @artist.name, artist_path(@artist) %>
      </td>
    </tr>
  </tbody>
</table>

<div class='row'>
  <%= render 'form' %>
</div>

app/views/artists/new.html.erb
<h1 class="col-sm-offset-2">New Artist</h1>

<%= render 'form' %>

app/views/artists/show.html.erb
<h3>
  <%= favorite_widget @artist, artist_path(@artist) %>
  <%= @artist.name %>
  <%= link_to edit_artist_path(@artist) do %>
    <span class="glyphicon glyphicon-pencil" aria-hidden="true">
    </span>
  <% end %>
</h3>

<p>
  <% @artist.songs_by_record.each do |record, songs| %>
    <%= render partial: 'shared/record_header', locals: { record: record } %>
    <% songs.each do |song| %>
      <div class='row song'>
        <div class='col-xs-1'><%= song.ordinal %></div>
        <div class='col-xs-2 time'>2:33</div>
        <div class='col-xs-6 title'>
          <%= favorite_widget song, favorite_record_song_path(record, song) %>
          <%= link_to song.title, record_song_path(song.record, song) %>
        </div>
      </div>
    <% end %>
    <br />
  <% end %>
</p>

<%= link_to 'Add Record', new_record_path(artist_ids: [@artist.id]), class: 'btn btn-primary' %>