config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/unprocessable_entity'

  get 'errors/internal_server_error'

  get 'errors/bad_request'

  resources :artists do
    member do
      patch '/favorite', action: 'favorite'
    end
  end

  resources :records do
    member do
      patch '/favorite', action: 'favorite'
    end
    resources :songs do
      member do
        patch '/favorite', action: 'favorite'
      end
    end
  end

  # account creation routes
  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  # session control routes
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  # root of the application
  root to: 'records#index'
end

app/models/record.rb
class Record < ActiveRecord::Base
  include MarkAsFavorite

  paginates_per 10
  max_paginates_per 50

  has_and_belongs_to_many :artists
  has_many :songs, dependent: :delete_all

  validates :title, presence: true, length: { minimum: 1 }
  validates :user_id, presence: true, numericality: { only_integer: true }, on: :create
  validate :user_id_not_changed, on: :update

  before_save :set_ordinal_letter

  def set_ordinal_letter
    words = title.downcase.split.reject{|e| e == 'the' || e == 'a' || e == 'an'}
    self.ordinal_letter = words.empty? ? title[0].downcase : words.first[0]
  end

private

  def user_id_not_changed
    if user_id_changed? && self.persisted?
      errors.add(:user_id, "Change of user_id not allowed!")
    end
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_filter :authorize
  include MarkingFavorites

  def model
    set_record { return }
    @record
  end

  # GET /records
  # GET /records.json
  def index
    @records = current_user.
      records.
      order(:ordinal_letter, :title).
      includes(:artists, :songs).
      page(params[:page]).
      per(params[:per_page] || 5)
    respond_to do |format|
      format.html {}
      format.json {}
      format.js do
        render partial: 'records/records_list', formats: ['html'], handlers: ['erb'], layout: false
      end
    end
  end

  # GET /records/1
  # GET /records/1.json
  def show
    set_record { return }
  end

  # GET /records/new
  def new
    @record = Record.new
    if params[:artist_ids]
      @record.artist_ids = Array(params[:artist_ids].map &:to_i)
    end
  end

  # GET /records/1/edit
  def edit
    set_record { return }
  end

  # POST /records
  # POST /records.json
  def create
    @record = Record.new(record_params.merge(user_id: current_user.id))
    respond_to do |format|
      if @record.save
        format.html { redirect_to @record, notice: 'Record was successfully created.' }
        format.json { render :show, status: :created, location: @record }
      else
        format.html { render :new }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /records/1
  # PATCH/PUT /records/1.json
  def update
    set_record { return }
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to @record, notice: 'Record was successfully updated.' }
        format.json { render :show, status: :ok, location: @record }
      else
        format.html { render :edit }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    set_record { return }
    @record.destroy
    respond_to do |format|
      format.html { redirect_to records_url, notice: 'Record was successfully destroyed.' }
      format.json { head :no_content }
      format.js { render nothing: true }
    end
  end

  private
    def set_record
      @record = Record.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      if json_request?
        render_bad_request { yield }
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def record_params
      params.require(:record).permit(:title, artist_ids: [])
    end
end

app/views/records/_details.html.erb
<% _show_title   = defined?(show_title)   ? show_title   : true       %>
<% _show_artists = defined?(show_artists) ? show_artists : true       %>
<% _show_songs   = defined?(show_songs)   ? show_songs   : true       %>
<% _size         = defined?(size)         ? size         : 'col-xs-7' %>

<div class='<%= _size %> single-record-details'>
  <% if _show_title %>
    <h3>
      <%= favorite_widget record, favorite_record_path(record) %>
      <%= record.title %>
      <%= link_to edit_record_path(record) do %>
        <span class="glyphicon glyphicon-pencil" aria-hidden="true">
        </span>
      <% end %>
    </h3>
  <% end %>

  <% if _show_artists %>
    <p>
      by:
      <span class='artist'>
        <%= render partial: 'inline_artists', locals: { record: record } %>
      </span>
    </p>
  <% end %>

  <% if _show_songs %>
    <p>
      <% record.songs.each_with_index do |song| %>
        <div class='row song'>
          <div class='col-xs-1'><%= song.ordinal %></div>
          <div class='col-xs-2 time'>2:33</div>
          <div class='col-xs-6 title'>
            <%= favorite_widget song, favorite_record_song_path(record, song) %>
            <%= link_to song.title, record_song_path(record, song) %>
          </div>
        </div>
      <% end %>
    </p>
  <% end %>
</div>

app/views/records/_form.html.erb
<%= form_for @record, html: {class: 'form form-horizontal'} do |f| %>
  <div class='row'>
    <div class='<%= @record.new_record? ? "col-sm-12" : "col-sm-6" %>'>
      <%= render partial: 'shared/form_field', locals: { form: f, model: @record, field_name: :title, field_type: :text_field, tab_index: 1 } %>
      <% content_for :artists_field do %>
        <%= f.collection_select :artist_ids, Artist.all, :id, :name, {select: (defined?(artist) ? artist.id : nil), blank: false}, {multiple: true, tabindex: 2, size: [Artist.count, 10].min} %>
      <% end %>
      <%= render partial: 'shared/form_field', locals: { form: f, model: @record, field_name: :artists, field_type: :collection_select } %>
    </div>

    <% unless @record.new_record? %>
    <div class='col-sm-6'>
      <%= render partial: 'details', locals: { record: @record, size: 'col-sm-6', show_title: false, show_artists: false } %>
    </div>
    <% end %>
  </div>

  <div class='row'>
    <div class='col-sm-offset-10 col-sm-2>'>
      <%= render partial: 'shared/submission_button', locals: { form: f, text: 'Save', tab_index: 2 } %>
    </div>
  </div>
<% end %>

app/views/records/_inline_artists.html.erb
<% record.artists.each do |artist| %>
  <%= favorite_widget artist, favorite_artist_path(artist) %>
  <%= link_to artist.name, artist %>
<% end %>

app/views/records/_list_artists.html.erb
<ul class="list-unstyled">
<% record.artists.each do |artist| %>
  <li>
    <%= favorite_widget artist, favorite_artist_path(artist) %>
    <%= link_to artist.name, artist %>
  </li>
<% end %>
<ul>

app/views/records/_records_list.html.erb
<div id='records'>
  <%= paginate @records, params: {controller: 'records', action: 'index', format: 'html'} %>

  <p>
    <% @records.each do |record| %>
      <%= render partial: 'shared/record_header', locals: { record: record } %>
      <%= render partial: 'inline_artists', locals: { record: record } %>
      <% if record.songs.blank? %>
        <div><%= link_to 'Add song', new_record_song_path(record), class: 'btn btn-primary' %></div>
      <% else %>
        <% record.songs.each do |song| %>
          <div class='row song'>
            <div class='col-xs-1'><%= song.ordinal %></div>
            <div class='col-xs-2 time'>2:33</div>
            <div class='col-xs-6 title'>
              <%= favorite_widget song, favorite_record_song_path(record, song) %>
              <%= link_to song.title, record_song_path(song.record, song) %>
            </div>
          </div>
        <% end %>
      <% end %>
      <br />
    <% end %>
  </p>
</div>

app/views/records/edit.html.erb
<table class='table table-condensed record-short'>
  <tbody>
    <tr>
      <td class='image'>
        <div class='record img-circle'>
        </div>
      </td>
      <td class='link'>
        <%= favorite_widget @record, favorite_record_path(@record) %>
        <%= link_to @record.title, record_path(@record) %>
      </td>
      <td>
        <%= link_to 'Add song', new_record_song_path(@record), class: 'btn btn-primary' %>
      </td>
    </tr>
  </tbody>
</table>

<div class='row'>
  <%= render 'form' %>
</div>

app/views/records/index.html.erb
<% if @records.blank? %>
  <div class="jumbotron">
    <h1>Hello, <%= current_user.name %></h1>
    <p>You haven't added any records yet. Why don't you get started?</p>
    <p>Use the <code>New Artist</code> or <code>New Record</code> buttons at the top of the site.</p>
  </div>
<% else %>
  <%= render partial: 'records_list' %>
<% end %>

app/views/records/new.html.erb
<h1>New Record</h1>

<%= render 'form' %>

app/views/records/show.html.erb
<div class='row'>
  <%= link_to 'Add song', new_record_song_path(@record), class: 'btn btn-primary' %>
</div>

<br />

<div class='row'>
  <div class='col-xs-5 single-record img-circle'>
  </div>
  <%= render partial: 'details', locals: { record: @record } %>
</div>