config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/unprocessable_entity'

  get 'errors/internal_server_error'

  get 'errors/bad_request'

  resources :artists do
    member do
      patch '/favorite', action: 'favorite'
    end
  end

  resources :records do
    member do
      patch '/favorite', action: 'favorite'
    end
    resources :songs do
      member do
        patch '/favorite', action: 'favorite'
      end
    end
  end

  # account creation routes
  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  # session control routes
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  # root of the application
  root to: 'records#index'
end

app/models/song.rb
class Song < ActiveRecord::Base
  include MarkAsFavorite

  belongs_to :record
  default_scope -> { order :ordinal }

  before_create -> (song) { song.ordinal ||= 1 }
  after_save :reorder

  validates :title, presence: true, length: { minimum: 1 }
  validates :record_id, presence: true, numericality: { only_integer: true }, on: :create
  validate :record_id_not_changed, on: :update

private

  def reorder
    # This algorithm relies on natural ordering. By putting myself at the front of the line
    # and then reordering by "ordinal", I'm guaranteed to come before any other song on my
    # record that has the same "ordinal" as me.
    _songs = record.songs.to_a
    _my_index = _songs.index(self)
    _songs.delete_at _my_index
    _songs.unshift self
    _songs.sort_by(&:ordinal).each_with_index do |s, index|
      s.update_column :ordinal, index + 1
    end
  end

  def record_id_not_changed
    if record_id_changed? && self.persisted?
      errors.add(:record_id, "Change of record_id not allowed!")
    end
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_filter :authorize
  include MarkingFavorites

  def model
    validate_parameters { return }
    @song
  end

  # GET /records/1/songs/1
  # GET /records/1/songs/1.json
  def show
    validate_parameters { return }
  end

  # GET /records/1/songs/new
  def new
    @song = Song.new(record_id: params[:record_id])
  end

  # GET /records/1/songs/1/edit
  def edit
    validate_parameters { return }
  end

  # POST /records/1/songs
  # POST /records/1/songs.json
  def create
    @song = Song.new(song_params)

    begin
      respond_to do |format|
        if @song.save
          format.html { redirect_to @song.record, notice: 'Song was successfully created.' }
          format.json { render :show, status: :created }
        else
          format.html { render :new }
          format.json { render json: @song.errors, status: :unprocessable_entity }
        end
      end
    rescue ActiveRecord::RecordNotUnique
      @song.errors[:title] << "not unique for record"
      respond_to do |format|
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /records/1/songs/1
  # PATCH/PUT /records/1/songs/1.json
  def update
    validate_parameters { return }
    begin
      respond_to do |format|
        if @song.update(song_params)
          format.html { redirect_to @song.record, notice: 'Song was successfully updated.' }
          format.json { render :show, status: :ok, location: @song }
        else
          format.html { render :edit }
          format.json { render json: @song.errors, status: :unprocessable_entity }
        end
      end
    rescue ActiveRecord::RecordNotUnique
      @song.errors[:title] << "not unique for record"
      respond_to do |format|
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1/songs/1
  # DELETE /records/1/songs/1.json
  def destroy
    validate_parameters { return }
    @song.destroy
    respond_to do |format|
      format.html { redirect_to record_url(@song.record), notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:title, :ordinal).tap do |p|
        p[:record_id] = params[:record_id].to_i
      end
    end

    def validate_parameters
      @song = Song.find(params[:id])

      if @song.record_id != params[:record_id].to_i
        render_bad_request { yield }
      end

      @record = Record.find(params[:record_id])
    rescue ActiveRecord::RecordNotFound
      if json_request?
        render_bad_request { yield }
      end
    end
end

app/views/songs/_form.html.erb
<%= form_for [@song.record, @song] do |f| %>
  <div class='row'>
    <div class='col-xs-12'>
      <div class='row'>
      <%= render partial: 'shared/form_field', locals: { form: f, model: @song, field_name: :ordinal, field_type: :number_field, tab_index: 1, value: @song.ordinal || @song.record.songs.size + 1 } %>
      </div>

      <div class='row'>
      <%= render partial: 'shared/form_field', locals: { form: f, model: @song, field_name: :title, field_type: :text_field, tab_index: 2 } %>
      </div>

      <div class='row'>
      <%= render partial: 'shared/form_field', locals: { form: f, model: @song, field_name: :record_id, field_type: :hidden_field, tab_index: -1 } %>
      </div>
    </div>
    <div class='row'>
      <div class='col-xs-offset-5 col-xs-2'>
        <%= render partial: 'shared/submission_button', locals: { form: f, text: 'Save', tab_index: 2 } %>
      </div>
    </div>
  </div>
<% end %>
<script type='text/javascript'>
$('#song_ordinal').focus()
</script>

app/views/songs/edit.html.erb
<%= render partial: 'shared/record_header', locals: { record: @record } %>

<br />

<div class='row'>
  <div class='col-xs-6'>
    <%= render 'form' %>
  </div>
</div>

app/views/songs/new.html.erb
<%= render partial: 'shared/record_header', locals: { record: @record } %>

<br />

<div class='row'>
  <div class='col-xs-6'>
    <%= render 'form' %>
  </div>
</div>

app/views/songs/show.html.erb
<%= render partial: 'shared/record_header', locals: { record: @record } %>

<br />

<div class='row'>
  <div class='col-sm-1'><strong>Title:</strong></div>
  <div class='col-sm-11'>
    <%= favorite_widget @song, favorite_record_song_path(@record, @song) %>
    <%= @song.title %>
  </div>
</div>

<div class='row'>
  <div class='col-sm-1'><strong>Time:</strong></div>
  <div class='col-sm-11'>2:33</div>
</div>

<br />

<%= link_to 'Edit', edit_record_song_path(@song.record, @song), class: 'btn btn-default' %>