config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/unprocessable_entity'

  get 'errors/internal_server_error'

  get 'errors/bad_request'

  resources :artists do
    member do
      patch '/favorite', action: 'favorite'
    end
  end

  resources :records do
    member do
      patch '/favorite', action: 'favorite'
    end
    resources :songs do
      member do
        patch '/favorite', action: 'favorite'
      end
    end
  end

  # account creation routes
  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  # session control routes
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  # root of the application
  root to: 'records#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Recordly</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body class='striped'>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class='container'>
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Recordly', root_path, class: 'navbar-brand' %>
      </div>
      <div id="navbar" class="collapse navbar-collapse pull-right">
        <ul class="nav navbar-nav">
          <% if current_user %>
            <li><%= link_to 'New Artist', new_artist_path, class: 'btn btn-xs btn-default' %></li>
            <li>&nbsp;</li>
            <li><%= link_to 'New Record', new_record_path, class: 'btn btn-xs btn-default' %></li>
          <% end %>
        </ul>
        <ul class="nav navbar-nav">
          <% if current_user %>
            <li class='current-user'><%= current_user.name %></li>
            <li><%= link_to 'Logout', logout_path %></li>
          <% else %>
            <li><%= link_to 'Login', login_path %></li>
            <li><%= link_to 'Create an Account', signup_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <div class='container'>
    <div class='app'>
      <%= yield %>
    </div>
  </div>
</body>
</html>